from __future__ import annotations

from .settings import apply_legacy_env_defaults

apply_legacy_env_defaults()

from database import (  # noqa: E402
    AIConfig,
    AIModelSettings,
    AILog,
    FollowupCampaign,
    FollowupDelivery,
    FollowupDeliveryAttempt,
    FollowupRun,
    FollowupStep,
    Base,
    CaseStudy,
    Content,
    ContentMedia,
    KnowledgeBase,
    Mailing,
    MediaCollection,
    MediaLibrary,
    Message,
    PromoCode,
    RandomMessage,
    ReferralPaymentLog,
    ReferralTemplate,
    RobokassaPayment,
    SecretTestQuestion,
    SubscriptionConfig,
    SubscriptionPlan,
    TestAttempt,
    TestConfig,
    TestQuestion,
    TestSession,
    Topic,
    followup_campaign_topic_association,
    TopicMediaDeck,
    TrialUsageHistory,
    User,
    UserSubscription,
    UserTopicState,
    YookassaPayment,
    async_session_maker,
    engine,
    get_all_admin_ids,
    init_db,
    media_collection_items,
    topic_collection_association,
)
